project:
  owner: quickstart-eng@amazon.com
  name: quickstart-microsoft-pki
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
tests:
  quickstart-microsoft-pki-1tier:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      DomainAdminPassword: $[taskcat_genpass_16]
      KeyPairName: $[taskcat_getkeypair]
      NumberOfRDGWHosts: '0'
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RDGWCIDR: 0.0.0.0/0
      CADeploymentType: One-Tier
    regions:
    - ap-northeast-1
    - ap-southeast-1
    - ca-central-1
    - eu-west-1
    - us-east-1
    - us-west-1
    template: templates/microsoft-pki-main.template.yaml

  quickstart-microsoft-pki-2tier:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      DomainAdminPassword: $[taskcat_genpass_16]
      KeyPairName: $[taskcat_getkeypair]
      NumberOfRDGWHosts: '0'
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RDGWCIDR: 0.0.0.0/0
      CADeploymentType: Two-Tier
    regions:
    - ap-northeast-2
    - ap-southeast-2
    - eu-central-1
    - eu-west-2
    - us-east-2
    - us-west-2
    template: templates/microsoft-pki-main.template.yaml