project:
  owner: quickstart-eng@amazon.com
  name: quickstart-microsoft-pki
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  template: templates/microsoft-pki-master.template.yaml
 
tests:
  quickstart-microsoft-pki:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      DomainAdminPassword: $[taskcat_genpass_16]
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RDGWCIDR: 0.0.0.0/0
    regions:
    - ap-northeast-1
#    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
#    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2