AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template creates a Microsoft one-tier or two-tie PKI infrastructure.
  **WARNING** This template creates Amazon EC2 Windows instances and related resources. 
  You will be billed for the AWS resources used if you create a stack from this template. (qs-1qpclo7fi)
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Parameters for deploying into an existing VPC"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VPCCIDR
          - VPCID
          - CaServerSubnet
          - DomainMembersSG
      - Label:
          default: Amazon EC2 Configuration
        Parameters:
          - OrCaServerInstanceType
          - OrCaDataDriveSizeGiB
          - EntCaServerInstanceType
          - EntCaDataDriveSizeGiB
          - KeyPairName
          - AMI
      - Label:
          default: Microsoft Active Directory Domain Services Configuration
        Parameters:
          - DomainDNSName
          - DomainNetBIOSName
          - DomainController1IP
          - DomainController2IP
          - AdministratorSecret
          - DirectoryType
      - Label:
          default: Microsoft Active Directory Certificate Services Configuration
        Parameters:
          - CADeploymentType
          - OrCaServerNetBIOSName
          - EntCaServerNetBIOSName
          - CaKeyLength
          - CaHashAlgorithm
          - OrCaValidityPeriodUnits
          - CaValidityPeriodUnits
          - UseS3ForCRL
          - S3CRLBucketName
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
    ParameterLabels:
      VPCCIDR:
        default: VPC CIDR
      VPCID:
        default: VPC ID
      CaServerSubnet:
        default: CA(s) Subnet ID
      DomainMembersSG:
        default: Security Group ID for Domain Members Security Group.  
      OrCaServerInstanceType:
        default: Offline Root CA Instance Type (Only Used For Two Tier PKI)
      OrCaDataDriveSizeGiB:
        default: Size of the Data Drive in GiB for Offline Root CA (Only Used For Two Tier PKI)
      EntCaServerInstanceType:
        default: Enterprise Root or Subordinate CA Instance Type
      EntCaDataDriveSizeGiB:
        default: Size of the Data Drive in GiB for Enterprise Root or Subordinate CA
      KeyPairName:
        default: Key pair name
      AMI:
        default: SSM Parameter Value to grab the lastest AMI ID
      DomainDNSName:
        default: Domain FQDN DNS name
      DomainNetBIOSName:
        default: Domain NetBios name
      DomainController1IP:
        default: IP For Domain Controller that Offline Root (Only Used For Two Tier PKI) & Enterprise CA Instance will use for DNS
      DomainController2IP:
        default: IP For Domain Controller that Offline Root (Only Used For Two Tier PKI) & Enterprise Root or Subordinate CA Instance will use for DNS
      AdministratorSecret:
        default: The arn for the Secret containing the domain CA Install Credentials
      DirectoryType:
        default: Type of Active Directory CA(s) will be integrated with
      CADeploymentType:
        default: Do you want to Deploy Two Tier or One Tier PKI Infrastructure
      OrCaServerNetBIOSName:
        default: Offline Root CA NetBIOS Name (Only Used For Two Tier PKI)
      EntCaServerNetBIOSName:
        default: Enterprise Root or Subordinate CA NetBIOS Name
      CaKeyLength:
        default: CA Key Length
      CaHashAlgorithm:
        default: CA Hash Algorithm
      OrCaValidityPeriodUnits:
        default: Offline Root CA Certificate Validity Period in Years (Only Used For Two Tier PKI)
      CaValidityPeriodUnits:
        default: Enterprise Root or Subordinate CA Certificate Validity Period in Years
      UseS3ForCRL:
        default: Use S3 for CA(s) CRL location
      S3CRLBucketName:
        default: S3 bucket name for CA(s) CRL
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
Parameters:
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR Block for the VPC
    Type: String
  VPCID:
    Description: ID of the VPC (e.g., vpc-0343606e)
    Type: AWS::EC2::VPC::Id
  CaServerSubnet:
    Description: ID of the CA(s) subnet (e.g., subnet-a0246dcd)
    Type: AWS::EC2::Subnet::Id
  DomainMembersSG:
    Description: Security Group ID for Domain Members Security Group.  
    Type: AWS::EC2::SecurityGroup::Id
  OrCaServerInstanceType:
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large
      - t3a.small
      - t3a.medium
      - t3a.large
    Default: t3.medium
    Description: Amazon EC2 instance type for the Offline Root CA instance (Only Used For Two Tier PKI)
    Type: String
  OrCaDataDriveSizeGiB:
    Type: 'Number'
    Default: '2'
    Description: Size of the Data Drive in GiB for Offline Root CA (Only Used For Two Tier PKI)
  EntCaServerInstanceType:
    AllowedValues:
      - t2.small
      - t3.small
      - t2.medium
      - t3.medium
      - t2.large
      - t3.large
    Default: t3.medium
    Description: Amazon EC2 instance type for the Enterprise Root or Subordinate CA instance
    Type: String
  EntCaDataDriveSizeGiB:
    Type: 'Number'
    Default: '2'
    Description: Size of the Data Drive in GiB for Enterprise Root or Subordinate CA
  KeyPairName:
    Description: Name of the key pair that you will use to securely connect to your EC2 instance after it launches.
    Type: AWS::EC2::KeyPair::KeyName
  AMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-windows-latest/Windows_Server-2019-English-Full-Base'
    Description: CA(s) SSM Parameter Value to grab the lastest AMI ID
  DomainDNSName:
    AllowedPattern: '[a-zA-Z0-9\-]+\..+'
    Description: Fully qualified domain name (FQDN) of the forest root domain e.g. example.com
    MaxLength: '255'
    MinLength: '2'
    Type: String
  DomainNetBIOSName:
    AllowedPattern: '[a-zA-Z0-9\-]+'
    Description: NetBIOS name of the domain (up to 15 characters) for users of earlier versions of Windows e.g. EXAMPLE
    MaxLength: '15'
    MinLength: '1'
    Type: String
  DomainController1IP:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
    Description: IP For Domain Controller that Offline Root (Only Used For Two Tier PKI) & Enterprise Root or Subordinate CA Instance will use for DNS
    Type: String
  DomainController2IP:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
    Description: IP For Domain Controller that Offline Root (Only Used For Two Tier PKI) & Enterprise Root or Subordinate CA Instance will use for DNS
    Type: String
  AdministratorSecret:
    Description: The arn for the Secret containing the CA Install Credentials
    Type: String
  DirectoryType:
    Description: Type of Active Directory CA(s) will be integrated with, AWS Managed Microsoft AD or Self Managed AD
    AllowedValues:
      - 'AWSManaged'
      - 'SelfManaged'
    Type: String
  CADeploymentType:
    AllowedValues:
      - 'One-Tier'
      - 'Two-Tier'
    Default: 'Two-Tier'
    Description: Do you want to Deploy Two Tier or One Tier PKI Infrastructure
    Type: String
  OrCaServerNetBIOSName:
    AllowedPattern: '[a-zA-Z0-9\-]+'
    Description: NetBIOS name of the Offline Root CA server (Only Used For Two Tier PKI) (up to 15 characters)
    MaxLength: '15'
    MinLength: '1'
    Type: String
    Default: ORCA1
  EntCaServerNetBIOSName:
    AllowedPattern: '[a-zA-Z0-9\-]+'
    Description: NetBIOS name of the Enterprise Root or Subordinate CA server (up to 15 characters)
    MaxLength: '15'
    MinLength: '1'
    Type: String
    Default: ENTCA1
  CaKeyLength:
    Description: CA(s) Key Length
    AllowedValues:
      - '2048'
      - '4096'
    Default: '2048'
    Type: String
  CaHashAlgorithm:
    Description: CA(s) Hash Algorithm
    AllowedValues:
      - 'SHA256'
      - 'SHA384'
      - 'SHA512'
    Default: 'SHA256'
    Type: String
  OrCaValidityPeriodUnits:
    Description: Offline Root CA Certificate Validity Period in Years (Only Used For Two Tier PKI)
    Default: '10'
    Type: String
  CaValidityPeriodUnits:
    Description: Enterprise Root or Subordinate CA Certificate Validity Period in Years
    Default: '5'
    Type: String
  UseS3ForCRL:
    Description: Use S3 for CA(s) CRL location
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'No'
    Type: String
  S3CRLBucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Default: examplebucket
    Description: S3 bucket name for CA(s) CRL. Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: Name of the S3 bucket for your copy of the Quick Start assets. Keep the default name unless you are customizing the template. Changing the name updates code references to point to a new Quick Start location. This name can include numbers, lowercase letters, uppercase letters, and hyphens, but do not start or end with a hyphen (-). See https://aws-quickstart.github.io/option1.html.
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. Keep the default Region unless you are customizing the template. Changing this Region updates code references to point to a new Quick Start location. When using your own bucket, specify the Region. See https://aws-quickstart.github.io/option1.html.'
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-microsoft-pki/
    Description: S3 key prefix that is used to simulate a directory for your copy of the Quick Start assets. Keep the default prefix unless you are customizing the template. Changing this prefix updates code references to point to a new Quick Start location. This prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slashes (/). See https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html and https://aws-quickstart.github.io/option1.html.
    Type: String
Rules:
  SubnetsInVPC:
    Assertions:
      - Assert: !EachMemberIn
          - !ValueOfAll
            - AWS::EC2::Subnet::Id
            - VpcId
          - !RefAll 'AWS::EC2::VPC::Id'
        AssertDescription: All subnets must in the VPC
  S3CRLBucketNameValidation:
    RuleCondition: !Equals
      - !Ref UseS3ForCRL
      - 'Yes'
    Assertions:
      - AssertDescription: CRL BucketName cannot must be valid BucketName
        Assert: !Not [!Equals [!Ref S3CRLBucketName, 'examplebucket']]
Conditions:
  GovCloudCondition: !Equals
    - !Ref 'AWS::Region'
    - us-gov-west-1
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
  UsingS3BucketForCrl: !Equals [!Ref UseS3ForCRL, 'Yes']
  ShouldCreateOneTierPkiResource: !Equals [!Ref CADeploymentType, 'One-Tier']
  ShouldCreateTwoTierPkiResource: !Equals [!Ref CADeploymentType, 'Two-Tier']
Resources:
  OneTierCAStack:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateOneTierPkiResource
    Properties:
      TemplateURL:
        Fn::Sub:
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/one-tier.template'
          - S3Region: !If
              - UsingDefaultBucket
              - !Ref AWS::Region
              - !Ref QSS3BucketRegion
            S3Bucket: !If
              - UsingDefaultBucket
              - !Sub '${QSS3BucketName}-${AWS::Region}'
              - !Ref QSS3BucketName
      Parameters:
        VPCCIDR: !Ref 'VPCCIDR'
        VPCID: !Ref 'VPCID'
        EntCaServerSubnet: !Ref 'CaServerSubnet'
        DomainMembersSG: !Ref 'DomainMembersSG'
        EntCaServerInstanceType: !Ref 'EntCaServerInstanceType'
        EntCaDataDriveSizeGiB: !Ref 'EntCaDataDriveSizeGiB'
        KeyPairName: !Ref 'KeyPairName'
        AMI: !Ref 'AMI'
        DomainDNSName: !Ref 'DomainDNSName'
        DomainNetBIOSName: !Ref 'DomainNetBIOSName'
        DomainController1IP: !Ref 'DomainController1IP'
        DomainController2IP: !Ref 'DomainController2IP'
        AdministratorSecret: !Ref 'AdministratorSecret'
        DirectoryType: !Ref DirectoryType
        EntCaServerNetBIOSName: !Ref 'EntCaServerNetBIOSName'
        EntCaKeyLength: !Ref 'CaKeyLength'
        EntCaHashAlgorithm: !Ref 'CaHashAlgorithm'
        EntCaValidityPeriodUnits: !Ref 'CaValidityPeriodUnits'
        UseS3ForCRL: !Ref 'UseS3ForCRL'
        S3CRLBucketName: !Ref 'S3CRLBucketName'
        QSS3BucketName: !Ref 'QSS3BucketName'
        QSS3BucketRegion: !Ref 'QSS3BucketRegion'
        QSS3KeyPrefix: !Ref 'QSS3KeyPrefix'
  TwoTierCAStack:
    Type: AWS::CloudFormation::Stack
    Condition: ShouldCreateTwoTierPkiResource
    Properties:
      TemplateURL:
        Fn::Sub:
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/two-tier.template'
          - S3Region: !If
              - UsingDefaultBucket
              - !Ref AWS::Region
              - !Ref QSS3BucketRegion
            S3Bucket: !If
              - UsingDefaultBucket
              - !Sub '${QSS3BucketName}-${AWS::Region}'
              - !Ref QSS3BucketName
      Parameters:
        VPCCIDR: !Ref 'VPCCIDR'
        VPCID: !Ref 'VPCID'
        OrCaServerSubnet: !Ref 'CaServerSubnet'
        SubCaServerSubnet: !Ref 'CaServerSubnet'
        DomainMembersSG: !Ref 'DomainMembersSG'
        OrCaServerInstanceType: !Ref 'OrCaServerInstanceType'
        OrCaDataDriveSizeGiB: !Ref 'OrCaDataDriveSizeGiB'
        SubCaServerInstanceType: !Ref 'EntCaServerInstanceType'
        SubCaDataDriveSizeGiB: !Ref 'EntCaDataDriveSizeGiB'
        KeyPairName: !Ref 'KeyPairName'
        AMI: !Ref 'AMI'
        DomainDNSName: !Ref 'DomainDNSName'     
        DomainNetBIOSName: !Ref 'DomainNetBIOSName'   
        DomainController1IP: !Ref 'DomainController1IP'
        DomainController2IP: !Ref 'DomainController2IP'
        AdministratorSecret: !Ref 'AdministratorSecret'
        DirectoryType: !Ref DirectoryType
        OrCaServerNetBIOSName: !Ref 'OrCaServerNetBIOSName'
        SubCaServerNetBIOSName: !Ref 'EntCaServerNetBIOSName'  
        OrCaKeyLength: !Ref 'CaKeyLength'
        SubCaKeyLength: !Ref 'CaKeyLength'
        OrCaHashAlgorithm: !Ref 'CaHashAlgorithm'
        SubCaHashAlgorithm: !Ref 'CaHashAlgorithm'
        OrCaValidityPeriodUnits: !Ref 'OrCaValidityPeriodUnits'
        SubCaValidityPeriodUnits: !Ref 'CaValidityPeriodUnits'
        UseS3ForCRL: !Ref 'UseS3ForCRL'
        S3CRLBucketName: !Ref 'S3CRLBucketName'
        QSS3BucketName: !Ref 'QSS3BucketName'
        QSS3BucketRegion: !Ref 'QSS3BucketRegion'
        QSS3KeyPrefix: !Ref 'QSS3KeyPrefix'